vich_uploader:
    db_driver: orm

    mappings:
        logos:
            uri_prefix: /img/custom/logos
            upload_destination: '%kernel.project_dir%/public/img/custom/logos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
